import {
  hiscoresTable,
  usersTable,
  eventsTable,
  skillsTable,
  session,
  account,
  verification,
  skillEventsTable,
  activityEventsTable,
  activitiesTable,
  membersTable,
} from './schema.ts'

// For full row type (all columns)
export type Hiscore = typeof hiscoresTable.$inferSelect
export type User = typeof usersTable.$inferSelect
export type Event = typeof eventsTable.$inferSelect
export type Skill = typeof skillsTable.$inferSelect
export type Session = typeof session.$inferSelect
export type Account = typeof account.$inferSelect
export type Verification = typeof verification.$inferSelect
export type SkillEvent = typeof skillEventsTable.$inferSelect
export type ActivityEvent = typeof activityEventsTable.$inferSelect
export type Activity = typeof activitiesTable.$inferSelect
export type Member = typeof membersTable.$inferSelect

// For insert operations (excludes auto-generated columns)
export type NewHiscore = typeof hiscoresTable.$inferInsert
export type NewUser = typeof usersTable.$inferInsert
export type NewEvent = typeof eventsTable.$inferInsert
export type NewSkill = typeof skillsTable.$inferInsert
export type NewSession = typeof session.$inferInsert
export type NewAccount = typeof account.$inferInsert
export type NewVerification = typeof verification.$inferInsert
export type NewSkillEvent = typeof skillEventsTable.$inferInsert
export type NewActivityEvent = typeof activityEventsTable.$inferInsert
export type NewActivity = typeof activitiesTable.$inferInsert
export type NewMember = typeof membersTable.$inferInsert

export enum ClanRanks {
  // Fixed ranks
  Owner = 'Owner',
  DeputyOwner = 'Deputy Owner',
  Administrator = 'Administrator',
  Guest = 'Guest',

  // Army ranks 1
  // Dogsbody = 'Dogsbody',
  // Minion = 'Minion',
  // Recruit = 'Recruit',
  // Pawn = 'Pawn',
  // Private = 'Private',
  // Corporal = 'Corporal',
  // Novice = 'Novice',
  // Sergeant = 'Sergeant',
  // Cadet = 'Cadet',

  // Army ranks 2
  // Page = 'Page',
  // Noble = 'Noble',
  // Adept = 'Adept',
  // Legionnaire = 'Legionnaire',
  // Lieutenant = 'Lieutenant',
  // Proselyte = 'Proselyte',
  // Captain = 'Captain',
  // Major = 'Major',
  // General = 'General',
  // Master = 'Master',

  // Army ranks 3
  // Officer = 'Officer',
  // Commander = 'Commander',
  // Colonel = 'Colonel',
  // Brigadier = 'Brigadier',
  // Admiral = 'Admiral',
  // Marshal = 'Marshal',

  // Gemstones
  // Opal = 'Opal',
  // Jade = 'Jade',
  // RedTopaz = 'Red Topaz',
  // Sapphire = 'Sapphire',
  // Emerald = 'Emerald',
  // Ruby = 'Ruby',
  // Diamond = 'Diamond',
  // Dragonstone = 'Dragonstone',
  // Onyx = 'Onyx',
  // Zenyte = 'Zenyte',

  // Non-human
  // Kitten = 'Kitten',
  // Bob = 'Bob',
  // Wily = 'Wily',
  // Hellcat = 'Hellcat',
  // Skulled = 'Skulled',
  // Goblin = 'Goblin',
  // Beast = 'Beast',
  // Imp = 'Imp',
  // GnomeChild = 'Gnome Child',
  // GnomeElder = 'Gnome Elder',
  // ShortGreenGuy = 'Short Green Guy',

  // Regions
  // Misthalinian = 'Misthalinian',
  // Karamjan = 'Karamjan',
  // Asgarnian = 'Asgarnian',
  // Kharidian = 'Kharidian',
  // Morytanian = 'Morytanian',
  // Wild = 'Wild',
  // Kandarin = 'Kandarin',
  // Fremennik = 'Fremennik',
  // Tirannian = 'Tirannian',

  // Religions
  // Brassican = 'Brassican',
  // Saradominist = 'Saradominist',
  // Guthixian = 'Guthixian',
  // Zamorakian = 'Zamorakian',
  // Serenist = 'Serenist',
  // Bandosian = 'Bandosian',
  // Zarosian = 'Zarosian',
  // Armadylean = 'Armadylean',
  // Xerician = 'Xerician',

  // Rune symbols
  // Air = 'Air',
  // Mind = 'Mind',
  // Water = 'Water',
  // Earth = 'Earth',
  // Fire = 'Fire',
  // Body = 'Body',
  // Cosmic = 'Cosmic',
  // Chaos = 'Chaos',
  // Nature = 'Nature',
  // Law = 'Law',
  // Death = 'Death',
  // Astral = 'Astral',
  // Blood = 'Blood',
  // Soul = 'Soul',
  // Wrath = 'Wrath',

  // Trees
  // Diseased = 'Diseased',
  // Pine = 'Pine',
  // Wintumber = 'Wintumber',
  // Oak = 'Oak',
  // Willow = 'Willow',
  // Maple = 'Maple',
  // Yew = 'Yew',
  // Blisterwood = 'Blisterwood',
  // Magic = 'Magic',

  // Skills
  Attacker = 'Attacker',
  Enforcer = 'Enforcer',
  Defender = 'Defender',
  Ranger = 'Ranger',
  Priest = 'Priest',
  Magician = 'Magician',
  Runecrafter = 'Runecrafter',
  Medic = 'Medic',
  Athlete = 'Athlete',
  Herbologist = 'Herbologist',
  Thief = 'Thief',
  Crafter = 'Crafter',
  Fletcher = 'Fletcher',
  Miner = 'Miner',
  Smith = 'Smith',
  Fisher = 'Fisher',
  Cook = 'Cook',
  Firemaker = 'Firemaker',
  Lumberjack = 'Lumberjack',
  Slayer = 'Slayer',
  Farmer = 'Farmer',
  Constructor = 'Constructor',
  Hunter = 'Hunter',
  Skiller = 'Skiller',
  Competitor = 'Competitor',

  // Capes
  Holy = 'Holy',
  Unholy = 'Unholy',
  Natural = 'Natural',
  Sage = 'Sage',
  Destroyer = 'Destroyer',
  Mediator = 'Mediator',
  Legend = 'Legend',
  Myth = 'Myth',
  TzTok = 'TzTok',
  TzKal = 'TzKal',
  Maxed = 'Maxed',

  // Skilling-focused
  Anchor = 'Anchor',
  Apothecary = 'Apothecary',
  Merchant = 'Merchant',
  Feeder = 'Feeder',
  Harpoon = 'Harpoon',
  Carry = 'Carry',

  // Combat-focused
  // Archer = 'Archer',
  // Battlemage = 'Battlemage',
  // Artillery = 'Artillery',
  // Infantry = 'Infantry',
  // Smiter = 'Smiter',
  // Looter = 'Looter',
  // Saviour = 'Saviour',
  // Sniper = 'Sniper',
  // Crusader = 'Crusader',
  // Spellcaster = 'Spellcaster',

  // Miscellaneous 1
  // Mentor = 'Mentor',
  // Prefect = 'Prefect',
  // Leader = 'Leader',
  // Supervisor = 'Supervisor',
  // Superior = 'Superior',
  // Executive = 'Executive',
  // Senator = 'Senator',
  // Monarch = 'Monarch',
  // Scavenger = 'Scavenger',
  // Labourer = 'Labourer',
  // Worker = 'Worker',
  // Forager = 'Forager',
  // Hoarder = 'Hoarder',
  // Prospector = 'Prospector',
  // Gatherer = 'Gatherer',
  // Collector = 'Collector',
  Bronze = 'Bronze',
  Iron = 'Iron',
  Steel = 'Steel',
  Gold = 'Gold',
  Mithril = 'Mithril',
  Adamant = 'Adamant',
  Rune = 'Rune',
  Dragon = 'Dragon',
  // Protector = 'Protector',
  // Bulwark = 'Bulwark',
  // Justiciar = 'Justiciar',
  // Sentry = 'Sentry',
  // Guardian = 'Guardian',
  // Warden = 'Warden',
  // Vanguard = 'Vanguard',
  // Templar = 'Templar',
  // Squire = 'Squire',
  // Duellist = 'Duellist',
  // Striker = 'Striker',
  // Ninja = 'Ninja',
  // Inquisitor = 'Inquisitor',
  // Expert = 'Expert',
  // Knight = 'Knight',
  // Paladin = 'Paladin',
  // Goon = 'Goon',
  // Brawler = 'Brawler',
  // Bruiser = 'Bruiser',
  // Scourge = 'Scourge',
  // Fighter = 'Fighter',
  // Warrior = 'Warrior',
  // Barbarian = 'Barbarian',
  // Berserker = 'Berserker',
  // Staff = 'Staff',
  // Crew = 'Crew',
  // Helper = 'Helper',
  // Moderator = 'Moderator',
  // Sheriff = 'Sheriff',

  // Miscellaneous 2
  // Red = 'Red',
  // Orange = 'Orange',
  // Yellow = 'Yellow',
  // Green = 'Green',
  // Blue = 'Blue',
  // Purple = 'Purple',
  // Pink = 'Pink',
  // Grey = 'Grey',
  // Wizard = 'Wizard',
  // Trickster = 'Trickster',
  // Illusionist = 'Illusionist',
  // Summoner = 'Summoner',
  // Necromancer = 'Necromancer',
  // Warlock = 'Warlock',
  // Witch = 'Witch',
  // Seer = 'Seer',
  // Assassin = 'Assassin',
  // Cutpurse = 'Cutpurse',
  // Bandit = 'Bandit',
  // Scout = 'Scout',
  // Burglar = 'Burglar',
  // Rogue = 'Rogue',
  // Smuggler = 'Smuggler',
  // Brigand = 'Brigand',
  Oracle = 'Oracle',
  Pure = 'Pure',
  Champion = 'Champion',
  // Epic = 'Epic',
  // Mystic = 'Mystic',
  // Hero = 'Hero',
  // Trialist = 'Trialist',
  // Defiler = 'Defiler',
  // Scholar = 'Scholar',
  // Councillor = 'Councillor',
  // Recruiter = 'Recruiter',
  // Learner = 'Learner',
  // Scribe = 'Scribe',
  // Assistant = 'Assistant',
  // Teacher = 'Teacher',
  // Coordinator = 'Coordinator',
  // Walker = 'Walker',
  // SpeedRunner = 'Speed-Runner',
  // Wanderer = 'Wanderer',
  // Pilgrim = 'Pilgrim',
  // Vagrant = 'Vagrant',
  // RecordChaser = 'Record-chaser',
  // Racer = 'Racer',
  // Strider = 'Strider',
  // Doctor = 'Doctor',
  // Nurse = 'Nurse',
  // Druid = 'Druid',
  // Healer = 'Healer',
  // Zealot = 'Zealot',
  // Cleric = 'Cleric',
  // Shaman = 'Shaman',
  // Therapist = 'Therapist',
  // Gamer = 'Gamer',
  // Adventurer = 'Adventurer',
  // Explorer = 'Explorer',
  Achiever = 'Achiever',
  Quester = 'Quester',
  // Raider = 'Raider',
  Completionist = 'Completionist',
  Elite = 'Elite',
  // Firestarter = 'Firestarter',
  // Specialist = 'Specialist',
  // Burnt = 'Burnt',
  // Pyromancer = 'Pyromancer',
  // Prodigy = 'Prodigy',
  // Ignitor = 'Ignitor',
  // Artisan = 'Artisan',
  // Legacy = 'Legacy',
}
